version: '3.4'

services:
  sit3232023t1task51:
    image: kingerit/calculator
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
